# Aula 1 - Primeiros passos na coleta de dados na internet

## Objetivos gerais

Neste primeiro encontro nos habituaremos ao ambiente de programação R e ao RStudio Server, interface na qual trabalharemos. Faremos alguns exercícios simples de aquisição de bases dados nos repositórios da Secretaria Estadual de Educação e do SEADE, bem como a raspagem de uma tabela em html do Wikipedia.

## Roteiro

1 - Faremos um encontro no Google Meets das 9h às 10h30 para apresentação do programa do curso e das e dos participantes. O link será enviado por e-mail.

2 - Ainda durante o encontro farei uma exposição rápida sobre os fundamentos da linguagem R e sobre como usar o RStudio.

3 - A seguir, faremos o [Tutorial 1], que trata da aquisição de arquivos de dados publicamente disponíveis para download, a exemplo de arquivos em formato .csv ou .xlsx. Veremos dois exemplos simples, um no repositório de dados da Secretaria Estadual de Educação e outro no repositório do SEADE

4 - Para encerrar o primeiro dia, faremos o Tutorial 2, que trata da "raspagem" de uma tabela em uma página de html, ou seja, da coleta da tabela diretamente no corpo da página e sua transformação em uma tabela e, posteriormente, de um arquivo em formato .csv. Utilizaremos um exemplo simples da Wikipedia.

5 - Às 12h nos encontraremos novamente no Google Meets para conversarmos sobre os tutoriais, e sobre as principais dificuldades.

## Traga seus problemas

Entre os encontros, por favor, pense se você tem em seu cotidiano algum desafio de automatização de coleta de dados. Se tiver, documente rapidamente, descrevendo o passo a passo do que costuma fazer manualmente, e me envie.